CartPole-v1:
  lr: 0.001
  discount: 0.99
  batch_size: 64
  target_update_steps: 25
  num_episodes: 3000
  memory_size: 50000
  epsilon: 0.1
  epsilon_decay: 0.995
  num_layers: 3
  hidden_units: 512
Acrobot-v1:
  lr: 0.001
  discount: 0.99
  batch_size: 64
  target_update_steps: 25
  num_episodes: 3000
  memory_size: 50000
  epsilon: 0.1
  epsilon_decay: 0.995
  num_layers: 3
  hidden_units: 512
MountainCar-v0:
  lr: 0.001
  discount: 0.99
  batch_size: 64
  target_update_steps: 25
  num_episodes: 3000
  memory_size: 50000
  epsilon: 0.1
  epsilon_decay: 1
  num_layers: 3
  hidden_units: 256
LunarLander-v2:
  lr: 0.001
  discount: 0.99
  batch_size: 64
  target_update_steps: 25
  num_episodes: 3000
  memory_size: 50000
  epsilon: 0.1
  epsilon_decay: 0.995
  num_layers: 3
  hidden_units: 512
