CartPole-v1:
  lr: 0.001
  discount: 0.99
  lmbda: 0.95
  clip_ratio: 0.1
  epochs: 3
  update_steps: 8
  num_episodes: 3000
  num_layers: 2
  hidden_units: 32
Acrobot-v1:
  lr: 0.001
  discount: 0.99
  lmbda: 0.95
  clip_ratio: 0.1
  epochs: 3
  update_steps: 5
  num_episodes: 3000
  num_layers: 3
  hidden_units: 32
MountainCar-v0:
  lr: 0.001
  discount: 0.99
  lmbda: 0.95
  clip_ratio: 0.1
  epochs: 3
  update_steps: 5
  num_episodes: 3000
  num_layers: 3
  hidden_units: 32
